[package]
name = "crypto_kx"
version = "0.2.0-pre"
description = "Pure Rust implementation of libsodium's crypto_kx using BLAKE2"
authors = ["C4DT", "RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/crypto_kx"
homepage = "https://github.com/RustCrypto/nacl-compat"
repository = "https://github.com/RustCrypto/nacl-compat/tree/master/crypto_kx"
categories = ["cryptography", "no-std"]
keywords = ["nacl", "libsodium", "public-key", "blake2"]
edition = "2021"
rust-version = "1.60"

[dependencies]
blake2 = { version = "0.10", default-features = false }
rand_core = "0.6"

# optional dependencies
serdect = { version = "0.1", optional = true, default-features = false }

[target.'cfg(target_pointer_width = "32")'.dependencies]
x25519-dalek = { version = "1", default-features = false, features = ["u32_backend"] }

[target.'cfg(target_pointer_width = "64")'.dependencies]
x25519-dalek = { version = "1", default-features = false, features = ["u64_backend"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2", default-features = false, features = ["js"] }

[dev-dependencies]
rand_core = { version = "0.6", features = ["std"] }
sodiumoxide = "0.2"

[features]
serde = ["serdect"]
std = ["blake2/std", "rand_core/std", "x25519-dalek/std"]
