[workspace]
resolver = "2"
members = [
    "crypto_box",
    "crypto_kx",
    "crypto_secretbox",
    "crypto_secretstream",
]

[patch.crates-io]
ed25519-dalek = { git = "https://github.com/dalek-cryptography/ed25519-dalek" }