[package]
name = "test-vector-gen"
description = "Test vector generator which uses libsodium bindings"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
hex = "0.4.3"
hex-literal = "0.4"
libsodium-sys-stable = "1"
