name: crypto_box

on:
  pull_request:
    paths:
      - ".github/workflows/crypto_box.yml"
      - "crypto_box/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: crypto_box

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.60.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features chacha20
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features heapless
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features salsa20

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.60.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --release --no-default-features
      - run: cargo test --release
      - run: cargo test --release --features std
      - run: cargo test --release --features std,heapless
      - run: cargo test --release --features std,serde
      - run: cargo test --release --features std,seal

  cross:
    strategy:
      matrix:
        include:
          - target: armv7-unknown-linux-gnueabihf
            rust: stable
          - target: aarch64-unknown-linux-gnu
            rust: stable
          - target: powerpc-unknown-linux-gnu
            rust: stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ${{ matrix.deps }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - run: cargo install cross
      - run: cross test --release --target ${{ matrix.target }} --features std,serde,seal
